using UnityEngine;

public class Player : MonoBehaviour
{

    public int maxHealth = 100;
    public int currentHeatlh;

    public HealthBar healthBar;

    // Start is called once before the first execution of Update after the MonoBehaviour is created
    void Start()
    {
        currentHeatlh = maxHealth;
        healthBar.SetMaxHealth(maxHealth);
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetKeyDown(KeyCode.Space))
        {
            TakeDamage(20);
        }
    }


    void TakeDamage(int damage)
    {
        currentHeatlh -= damage;

        healthBar.SetHealth(currentHeatlh);
    }
}
